"""One-off: add NavBar-related keys to all 16 locales. Translations
authored in-session.
"""
from __future__ import annotations
import json
from pathlib import Path

MESSAGES = Path(__file__).resolve().parents[1] / "messages"

# nav.* additions
NAV_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "instructors":          "Instructors",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Guild Master Access",
        "unlockAllFeatures":    "Unlock all features",
        "upgrade":              "Upgrade",
        "coachingShort":        "Coaching Corner",
        "coachingSubtitle":     "1-on-1 video feedback",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Live calls & archives",
        "lockedTag":            "LOCKED",
        "toggleMenu":           "Toggle menu",
        "toggleNavMenu":        "Toggle navigation menu",
    },
    "es": {
        "instructors":          "Instructores",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Acceso Guild Master",
        "unlockAllFeatures":    "Desbloquea todas las funciones",
        "upgrade":              "Mejorar",
        "coachingShort":        "Rincón de Coaching",
        "coachingSubtitle":     "Feedback en video 1 a 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Llamadas en vivo y archivos",
        "lockedTag":            "BLOQUEADO",
        "toggleMenu":           "Abrir menú",
        "toggleNavMenu":        "Abrir menú de navegación",
    },
    "pt": {
        "instructors":          "Instrutores",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Acesso Guild Master",
        "unlockAllFeatures":    "Desbloqueie todos os recursos",
        "upgrade":              "Melhorar",
        "coachingShort":        "Cantinho do Coaching",
        "coachingSubtitle":     "Feedback em vídeo 1 a 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Chamadas ao vivo e arquivos",
        "lockedTag":            "BLOQUEADO",
        "toggleMenu":           "Abrir menu",
        "toggleNavMenu":        "Abrir menu de navegação",
    },
    "fr": {
        "instructors":          "Instructeurs",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Accès Guild Master",
        "unlockAllFeatures":    "Débloque toutes les fonctionnalités",
        "upgrade":              "Passer au niveau supérieur",
        "coachingShort":        "Coin du Coaching",
        "coachingSubtitle":     "Retour vidéo en 1-à-1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Appels en direct et archives",
        "lockedTag":            "VERROUILLÉ",
        "toggleMenu":           "Ouvrir le menu",
        "toggleNavMenu":        "Ouvrir le menu de navigation",
    },
    "de": {
        "instructors":          "Instruktoren",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Guild Master Zugang",
        "unlockAllFeatures":    "Alle Funktionen freischalten",
        "upgrade":              "Upgrade",
        "coachingShort":        "Coaching-Ecke",
        "coachingSubtitle":     "1-zu-1 Video-Feedback",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Live-Calls & Archive",
        "lockedTag":            "GESPERRT",
        "toggleMenu":           "Menü umschalten",
        "toggleNavMenu":        "Navigationsmenü umschalten",
    },
    "it": {
        "instructors":          "Istruttori",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Accesso Guild Master",
        "unlockAllFeatures":    "Sblocca tutte le funzioni",
        "upgrade":              "Aggiorna",
        "coachingShort":        "Angolo Coaching",
        "coachingSubtitle":     "Feedback video 1 a 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Chiamate dal vivo e archivi",
        "lockedTag":            "BLOCCATO",
        "toggleMenu":           "Apri menu",
        "toggleNavMenu":        "Apri menu di navigazione",
    },
    "ja": {
        "instructors":          "インストラクター",
        "blog":                 "ブログ",
        "admin":                "管理",
        "guildMasterAccess":    "Guild Master アクセス",
        "unlockAllFeatures":    "すべての機能を解除",
        "upgrade":              "アップグレード",
        "coachingShort":        "コーチングコーナー",
        "coachingSubtitle":     "1対1 ビデオフィードバック",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "ライブ通話とアーカイブ",
        "lockedTag":            "ロック中",
        "toggleMenu":           "メニュー切替",
        "toggleNavMenu":        "ナビゲーションメニュー切替",
    },
    "ko": {
        "instructors":          "강사",
        "blog":                 "블로그",
        "admin":                "관리",
        "guildMasterAccess":    "Guild Master 접근",
        "unlockAllFeatures":    "모든 기능 잠금 해제",
        "upgrade":              "업그레이드",
        "coachingShort":        "코칭 코너",
        "coachingSubtitle":     "1:1 비디오 피드백",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "라이브 통화와 아카이브",
        "lockedTag":            "잠김",
        "toggleMenu":           "메뉴 전환",
        "toggleNavMenu":        "내비게이션 메뉴 전환",
    },
    "zh": {
        "instructors":          "讲师",
        "blog":                 "博客",
        "admin":                "管理",
        "guildMasterAccess":    "Guild Master 访问权限",
        "unlockAllFeatures":    "解锁所有功能",
        "upgrade":              "升级",
        "coachingShort":        "教练角",
        "coachingSubtitle":     "1对1 视频反馈",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "实时通话与归档",
        "lockedTag":            "锁定",
        "toggleMenu":           "切换菜单",
        "toggleNavMenu":        "切换导航菜单",
    },
    "ru": {
        "instructors":          "Инструкторы",
        "blog":                 "Блог",
        "admin":                "Админ",
        "guildMasterAccess":    "Доступ Guild Master",
        "unlockAllFeatures":    "Разблокируй все функции",
        "upgrade":              "Улучшить",
        "coachingShort":        "Уголок коучинга",
        "coachingSubtitle":     "Видео-фидбек 1 на 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Прямые эфиры и архивы",
        "lockedTag":            "ЗАБЛОКИРОВАНО",
        "toggleMenu":           "Меню",
        "toggleNavMenu":        "Меню навигации",
    },
    "pl": {
        "instructors":          "Instruktorzy",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Dostęp Guild Master",
        "unlockAllFeatures":    "Odblokuj wszystkie funkcje",
        "upgrade":              "Ulepsz",
        "coachingShort":        "Kącik Coachingowy",
        "coachingSubtitle":     "Wideo feedback 1 na 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Rozmowy na żywo i archiwa",
        "lockedTag":            "ZABLOKOWANE",
        "toggleMenu":           "Przełącz menu",
        "toggleNavMenu":        "Przełącz menu nawigacji",
    },
    "nl": {
        "instructors":          "Instructeurs",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Guild Master toegang",
        "unlockAllFeatures":    "Ontgrendel alle functies",
        "upgrade":              "Upgrade",
        "coachingShort":        "Coaching-hoek",
        "coachingSubtitle":     "1-op-1 video-feedback",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Live gesprekken en archieven",
        "lockedTag":            "VERGRENDELD",
        "toggleMenu":           "Menu omschakelen",
        "toggleNavMenu":        "Navigatiemenu omschakelen",
    },
    "ar": {
        "instructors":          "المدربون",
        "blog":                 "المدونة",
        "admin":                "إدارة",
        "guildMasterAccess":    "وصول Guild Master",
        "unlockAllFeatures":    "افتح كل الميزات",
        "upgrade":              "ترقية",
        "coachingShort":        "زاوية التدريب",
        "coachingSubtitle":     "ملاحظات فيديو 1 إلى 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "مكالمات مباشرة وأرشيف",
        "lockedTag":            "مقفل",
        "toggleMenu":           "تبديل القائمة",
        "toggleNavMenu":        "تبديل قائمة التنقل",
    },
    "el": {
        "instructors":          "Εκπαιδευτές",
        "blog":                 "Blog",
        "admin":                "Διαχείριση",
        "guildMasterAccess":    "Πρόσβαση Guild Master",
        "unlockAllFeatures":    "Ξεκλείδωσε όλες τις λειτουργίες",
        "upgrade":              "Αναβάθμιση",
        "coachingShort":        "Γωνιά Coaching",
        "coachingSubtitle":     "Video feedback 1 προς 1",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Live κλήσεις και αρχεία",
        "lockedTag":            "ΚΛΕΙΔΩΜΕΝΟ",
        "toggleMenu":           "Εναλλαγή μενού",
        "toggleNavMenu":        "Εναλλαγή μενού πλοήγησης",
    },
    "sr": {
        "instructors":          "Инструктори",
        "blog":                 "Блог",
        "admin":                "Админ",
        "guildMasterAccess":    "Guild Master приступ",
        "unlockAllFeatures":    "Откључај све функције",
        "upgrade":              "Унапреди",
        "coachingShort":        "Кочинг кутак",
        "coachingSubtitle":     "1 на 1 видео фидбек",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Позиви уживо и архиве",
        "lockedTag":            "ЗАКЉУЧАНО",
        "toggleMenu":           "Отвори мени",
        "toggleNavMenu":        "Отвори навигациони мени",
    },
    "tr": {
        "instructors":          "Eğitmenler",
        "blog":                 "Blog",
        "admin":                "Admin",
        "guildMasterAccess":    "Guild Master Erişimi",
        "unlockAllFeatures":    "Tüm özellikleri aç",
        "upgrade":              "Yükselt",
        "coachingShort":        "Koçluk Köşesi",
        "coachingSubtitle":     "1-on-1 video geri bildirim",
        "roundtableShort":      "The Roundtable",
        "roundtableSubtitle":   "Canlı görüşmeler ve arşivler",
        "lockedTag":            "KİLİTLİ",
        "toggleMenu":           "Menüyü aç/kapat",
        "toggleNavMenu":        "Gezinme menüsünü aç/kapat",
    },
}


def main() -> None:
    expected = set(NAV_TRANSLATIONS["en"].keys())
    for loc in NAV_TRANSLATIONS:
        path = MESSAGES / f"{loc}.json"
        d = json.loads(path.read_text(encoding="utf-8"))
        d.setdefault("nav", {}).update(NAV_TRANSLATIONS[loc])
        path.write_text(json.dumps(d, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        missing = expected - set(d["nav"].keys())
        print(f"  {loc}: +{len(expected) - len(missing)} keys{' MISSING ' + str(missing) if missing else ' ok'}")


if __name__ == "__main__":
    main()
